######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 12 11:40:45 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml
# Input
HEADERS += agent.h
SOURCES += main.cpp agent.cpp
